version: '3.2'
services:
  freyr:
    ports:
      - "80:8080"
    image: golang
    volumes:
      - ./:/go/src/github.com/serdmanczyk/freyr/
    environment:
      GOPATH: /go/src/github.com/serdmanczyk/freyr/vendor/:/go
    working_dir: /go/src/github.com/serdmanczyk/freyr/
    command: go run main.go
  postgres:
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
