version: '3.2'
services:
  surtr:
    command: go test -v -tags=acceptance
    depends_on:
      - freyr
    env_file: ./cmd/surtr/.env
    image: golang
    links:
      - freyr
    volumes:
      - ./:/go/src/github.com/serdmanczyk/freyr/
    working_dir: /go/src/github.com/serdmanczyk/freyr/cmd/surtr
    environment:
      GOPATH: /go/src/github.com/serdmanczyk/freyr/vendor/:/go
