version: '3.2'
services:
  freyr:
    env_file: .env
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    build: 
      context: ./postgres/
    image: serdmanczyk/freyrpostgres
    env_file: ./postgres/.env
